### ISSUE TITLE
Best

### ISSUE THREAD

**Issue by TheSrBig** [5cmc/grim-trident#2]
rat

dont edit this... lmaoo

**Comment by Not-a-Tyler** [comment]
real

**Comment by K-K-L-L** [comment]
real

**Comment by rolkoztm** [comment]
😂😂Its not rst

**Comment by K-K-L-L** [comment]
> 😂😂Its not rst

It is.

**Comment by rolkoztm** [comment]
> > 😂😂Its not rst
> 
> It is.

I mean all what it does is send coords in chat

**Comment by integr-dev** [comment]
Yea this is very best indeed, as shown in the below image
<details>
  <summary>Image</summary>

![image](https://github.com/5cmc/grim-trident/assets/74710895/4c390654-c1b4-460c-b526-6a83c9196e98)

This code can be found in the "GrimDisabler" module in the given jar file (not on GitHub)

A brief rundown:

![image](https://github.com/5cmc/grim-trident/assets/74710895/f52bb799-308c-4e47-8ab3-5887e8d21a7c)

I mean... come on you could have obfuscated it...
</details>

**Comment by logykk** [comment]
> This code can be found in the "GrimDisabler" module in the given jar file (not on GitHub)
> 
> A brief rundown:

![nerd](https://github.com/5cmc/grim-trident/assets/35679186/668ded22-a81d-4d52-a212-baeaa1df8f6a)

**Comment by UncertainWater** [comment]
> Yea this is very best indeed, as shown in the below image
> 
> Image
> ![image](https://private-user-images.githubusercontent.com/74710895/322572222-4c390654-c1b4-460c-b526-6a83c9196e98.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NTQ1NjUsIm5iZiI6MTcxMzY1NDI2NSwicGF0aCI6Ii83NDcxMDg5NS8zMjI1NzIyMjItNGMzOTA2NTQtYzFiNC00NjBjLWI1MjYtNmE4M2M5MTk2ZTk4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDIzMDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjMGI1OWU4NjNmNTc4OGFlZTA3NTg5ZDk1MzY4ZTMwMmY4YTBjOTRjNzYyMDk4NGJlNjBjNTlkY2NiZWEzZmEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.N5uFKHUzi8f9I8odoCU5dNPDqYv8ExKO7PTpFg593GI)
> 
> This code can be found in the "GrimDisabler" module in the given jar file (not on GitHub)
> 
> A brief rundown:
> 
> ![image](https://private-user-images.githubusercontent.com/74710895/322575781-f52bb799-308c-4e47-8ab3-5887e8d21a7c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NTQ1NjUsIm5iZiI6MTcxMzY1NDI2NSwicGF0aCI6Ii83NDcxMDg5NS8zMjI1NzU3ODEtZjUyYmI3OTktMzA4Yy00ZTQ3LThhYjMtNTg4N2U4ZDIxYTdjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDIzMDQyNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMwNGQ5MTZiYzAzYWRlYjEzZjZmZWY0NzIxMDU3MTQwYzQxZjg1MmZmNmQzZTU1ZDRmODlkNzE3YTNkMDgyNjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0._ih3Qd9kFOKv1zTSuYdm_6XhfGXzBd0Jsnk6Pc9t__g)
> 
> I mean... come on you could have obfuscated it...

I love tridents.

**Comment by TheSrBig** [comment]
Rat proof: https://www.decompiler.com/jar/e739eb854aab43fc9c1fad74fcf50569/grim-trident-0.1.3.jar/codes/pristine/addon/mixin/ChatHudMixin.java

**Comment by UncertainWater** [comment]
> Rat proof: https://www.decompiler.com/jar/e739eb854aab43fc9c1fad74fcf50569/grim-trident-0.1.3.jar/codes/pristine/addon/mixin/ChatHudMixin.java

We can't see that

**Comment by TheSrBig** [comment]
https://web.archive.org/web/20240425185422/https://www.decompiler.com/jar/00214a18158041d2bec5cebd147b1a9b/ChatHudMixin.java

**Comment by TheSrBig** [comment]
> > Rat proof: https://www.decompiler.com/jar/e739eb854aab43fc9c1fad74fcf50569/grim-trident-0.1.3.jar/codes/pristine/addon/mixin/ChatHudMixin.java
> 
> 
> 
> We can't see that

https://web.archive.org/web/20240430053257/https://www.decompiler.com/jar/e739eb854aab43fc9c1fad74fcf50569/grim-trident-0.1.3.jar/codes/pristine/addon/mixin/ChatHudMixin.java

**Comment by ghost** [comment]
Closed issue as no dependency is affected.

**Comment by TheSrBig** [comment]
> > Rat proof: https://www.decompiler.com/jar/e739eb854aab43fc9c1fad74fcf50569/grim-trident-0.1.3.jar/codes/pristine/addon/mixin/ChatHudMixin.java
> 
> 
> 
> We can't see that

They deleted the link

**Comment by TheSrBig** [comment]
> Closed issue as no dependency is affected.

![image](https://github.com/5cmc/grim-trident/assets/89810837/e0a801f9-879e-4f32-a56f-8b64681975f9)
Why do you change the title?

**Comment by logykk** [comment]
No idea what you're talking about it's always been called that.
