### ISSUE TITLE
RAT

### ISSUE THREAD

**Issue by K-K-L-L** [5cmc/grim-trident#3]
proof: https://web.archive.org/web/20240425185422/https://www.decompiler.com/jar/00214a18158041d2bec5cebd147b1a9b/ChatHudMixin.java

**Comment by rolkoztm** [comment]
Its not. Ur retarded

**Comment by K-K-L-L** [comment]
> Its not. Ur retarded

It is, did you not read the code? retarted 5c member

**Comment by rolkoztm** [comment]
lmao i did. Its just a troll yall retarded fr

**Comment by K-K-L-L** [comment]
> lmao i did. Its just a troll yall retarded fr

random alt is gonna tell us that we're retarted, very cool

**Comment by rolkoztm** [comment]
> > lmao i did. Its just a troll yall retarded fr
> 
> random alt is gonna tell us that we're retarted, very cool

RAT - remote access trojan
This is definetly not remote access trojan
Cope about it

**Comment by K-K-L-L** [comment]
> > > lmao i did. Its just a troll yall retarded fr
> > 
> > 
> > random alt is gonna tell us that we're retarted, very cool
> 
> RAT - remote access trojan This is definetly not remote access trojan Cope about it

The code isn't directly accessing the victim's PC but it IS accessing the coords and doxxing the victim in chat which IS a rat.

Cope about it, you and that horrific grammar

**Comment by rolkoztm** [comment]
> > > > lmao i did. Its just a troll yall retarded fr
> > > 
> > > 
> > > random alt is gonna tell us that we're retarted, very cool
> > 
> > 
> > RAT - remote access trojan This is definetly not remote access trojan Cope about it
> 
> The code isn't directly accessing the victim's PC but it IS accessing the coords and doxxing the victim in chat which IS a rat.
> 
> Cope about it, you and that horrific grammar

Lmao doxing, what? Sending coords in chat isnt a rat 
Idrc about my grammar. Ur just mad again who.ru

**Comment by K-K-L-L** [comment]
> > > > > lmao i did. Its just a troll yall retarded fr
> > > > 
> > > > 
> > > > random alt is gonna tell us that we're retarted, very cool
> > > 
> > > 
> > > RAT - remote access trojan This is definetly not remote access trojan Cope about it
> > 
> > 
> > The code isn't directly accessing the victim's PC but it IS accessing the coords and doxxing the victim in chat which IS a rat.
> > Cope about it, you and that horrific grammar
> 
> Lmao doxing, what? Sending coords in chat isnt a rat Idrc about my grammar. Ur just mad again who.ru

I'm not mad, you are.

**Comment by MrBreakNFix** [comment]
this is not a rat, its just funny, build from src if you do not want cords sending feature
