### ISSUE TITLE
rat update

### ISSUE THREAD

**Issue by TheSrBig** [5cmc/grim-trident#5]
there is a compiled code in the mixin, I have uploaded it to wayback machine because they delete the original link 🙂‍↕️ 

Go outside and touch the grass![image](https://github.com/5cmc/grim-trident/assets/89810837/16ed06a0-083f-4cc8-998b-4caa7a8c1427)

**Comment by ghost** [comment]
Which link? I see no link attached.

**Comment by ghost** [comment]
After careful analysis this user posted the same link in another thread #2 This thread will be closed due to inactivity.

**Comment by TheSrBig** [comment]
You edited the post LMAOO

**Comment by TheSrBig** [comment]
> Which link? I see no link attached.

You edited the post. 🤣🤣🤦‍♂️

**Comment by TheSrBig** [comment]
> Which link? I see no link attached.

Again https://web.archive.org/web/20240425185422/https://www.decompiler.com/jar/00214a18158041d2bec5cebd147b1a9b/ChatHudMixin.java
